# Generated by Django 4.2.6 on 2023-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='slug',
        ),
    ]
